### PR TITLE
Update repo references

### PR DESCRIPTION
**Pull request by fouadhatem**
Update repo references from IBM-Swift to Kitura.

### CODE REVIEW

**Review by mbarnach — APPROVED** [review]

**Comment by mbarnach** [comment]
I don't know why the continuous integration is not working.

**Comment by futurejones** [comment]
@mbarnach could it be because the .travis.yml is still referencing https://github.com/IBM-Swift/Package-Builder.git?

**Comment by mbarnach** [comment]
Could be, but some others (like Kitura) are still referencing that file and they "failed normally"?!

**Comment by dannys42** [comment]
I force-merged one of your other patches just to get this change in.  I think I may have an idea of the issue... going to write more about it in Slack.

**Comment by dannys42** [comment]
Oops, sorry I forgot these were split up into different PR's.

**Pull request merged**
